name: Release Host Agent

permissions:
  contents: write
  
on:
  push:
    tags:
      - 'host-v*'  # Triggers on tags like host-v1.0.1
  workflow_dispatch:     # Allow manual trigger
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.1)'
        required: true
        type: string

env:
  # Electron build settings
  ELECTRON_CACHE: ~/.cache/electron
  ELECTRON_BUILDER_CACHE: ~/.cache/electron-builder

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
          - os: macos-latest  
            platform: darwin
          - os: ubuntu-latest
            platform: linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get version from tag or input
        id: version
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
            echo "tag_name=host-v${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            # Extract version from tag (host-v1.0.1 -> 1.0.1)
            VERSION=${GITHUB_REF#refs/tags/host-v}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Update package.json version
        shell: bash
        working-directory: host-agent
        run: |
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version

      - name: Install dependencies
        working-directory: host-agent
        run: |
          # Install dependencies without workspace conflicts
          npm install --no-workspaces

      - name: Setup virtual display and Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libnss3-dev libatk-bridge2.0-dev libdrm2 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libxss1 libasound2-dev
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Build Electron app (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: host-agent
        run: |
          npm run dist:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Electron app (macOS)
        if: matrix.os == 'macos-latest'
        working-directory: host-agent
        run: |
          echo "Starting macOS build..."
          npm run build
          npm run dist:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Electron app (Linux)
        if: matrix.os == 'ubuntu-latest'
        working-directory: host-agent
        run: |
          echo "Starting Linux build with sandbox disabled..."
          npm run build
          npm run dist:linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Disable sandbox for Linux CI environments
          ELECTRON_DISABLE_SANDBOX: 1
          # Additional Linux-specific flags
          DISPLAY: ":99"
          # Electron build environment
          USE_HARD_LINKS: false
          # Prevent native module compilation issues
          npm_config_cache: /tmp/.npm
          npm_config_prefer_offline: true

      - name: List build artifacts
        shell: bash
        working-directory: host-agent
        run: |
          echo "Build artifacts:"
          find release -type f -name "*.exe" -o -name "*.dmg" -o -name "*.AppImage" -o -name "*.deb" 2>/dev/null || echo "No artifacts found"

      - name: Create Release with GitHub CLI
        working-directory: host-agent
        shell: bash
        run: |
          # Debug GitHub CLI setup
          echo "Testing GitHub CLI..."
          echo "GitHub token length: ${#GH_TOKEN}"
          echo "Repository: ${{ github.repository }}"
          echo "Tag: ${{ steps.version.outputs.tag_name }}"
          
          # Test basic GitHub CLI functionality
          echo "Testing gh auth status..."
          gh auth status || echo "GitHub CLI auth failed"
          
          echo "Testing repository access..."
          gh repo view ${{ github.repository }} --json name || echo "Cannot access repository"
          
          # List available artifacts for this platform
          echo "Available artifacts:"
          ls -la release/ || echo "No release directory found"
          
          # Create release with available artifacts
          echo "Creating release..."
          ARTIFACTS=$(find release/ -name "*.exe" -o -name "*.dmg" -o -name "*.AppImage" -o -name "*.deb" 2>/dev/null | tr '\n' ' ')
          if [ -n "$ARTIFACTS" ]; then
            echo "Creating release with artifacts: $ARTIFACTS"
            gh release create ${{ steps.version.outputs.tag_name }} \
              --title "DisplayOps Host Agent v${{ steps.version.outputs.version }}" \
              --notes "Auto-generated release from GitHub Actions" \
              $ARTIFACTS || echo "Failed to create release with artifacts"
          else
            echo "No artifacts found, creating release without files"
            gh release create ${{ steps.version.outputs.tag_name }} \
              --title "DisplayOps Host Agent v${{ steps.version.outputs.version }}" \
              --notes "Auto-generated release from GitHub Actions" || echo "Failed to create release"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release completed
        run: |
          echo "Host Agent release created successfully on ${{ matrix.os }}!"
          echo "Host Agent apps can now auto-update to v${{ steps.version.outputs.version }}"