name: Release Browser Extension

on:
  push:
    tags:
      - 'ext-v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/extension-v}" >> $GITHUB_OUTPUT

      - name: Read manifest version
        id: manifest
        run: |
          MANIFEST_VERSION=$(grep -o '"version": "[^"]*"' browser-extension/manifest.json | grep -o '[0-9.]*')
          echo "MANIFEST_VERSION=$MANIFEST_VERSION" >> $GITHUB_OUTPUT

      - name: Package extension
        run: |
          cd browser-extension
          zip -r ../displayops-extension-${{ steps.get_version.outputs.VERSION }}.zip ./*
          cd ..
          ls -lh displayops-extension-*.zip

      - name: Generate checksum
        run: |
          sha256sum displayops-extension-${{ steps.get_version.outputs.VERSION }}.zip > displayops-extension-${{ steps.get_version.outputs.VERSION }}.zip.sha256
          cat displayops-extension-${{ steps.get_version.outputs.VERSION }}.zip.sha256

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Browser Extension v${{ steps.get_version.outputs.VERSION }}
          body: |
            ## DisplayOps Browser Extension v${{ steps.get_version.outputs.VERSION }}
            
            ### Installation
            1. Download `displayops-extension-${{ steps.get_version.outputs.VERSION }}.zip`
            2. Unzip the file
            3. Open Chrome/Edge and go to `chrome://extensions`
            4. Enable "Developer mode"
            5. Click "Load unpacked" and select the unzipped folder
            
            ### Changes
            - Manifest version: ${{ steps.manifest.outputs.MANIFEST_VERSION }}
            
            ### Checksums
            See attached `.sha256` file for verification
          draft: false
          prerelease: false

      - name: Upload Extension ZIP
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./displayops-extension-${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: displayops-extension-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./displayops-extension-${{ steps.get_version.outputs.VERSION }}.zip.sha256
          asset_name: displayops-extension-${{ steps.get_version.outputs.VERSION }}.zip.sha256
          asset_content_type: text/plain

